"""Versioned constants for the HWARANG ACADEMY pre-API simulator core."""
from __future__ import annotations

CUSTOMER_GENERATOR_VERSION = "1.0.0"
INSURANCE_GENERATOR_VERSION = "1.0.0"
COVERAGE_MAPPING_VERSION = "1.0.0"
COVERAGE_ANALYSIS_VERSION = "1.0.0"
EXCEL_TEMPLATE_VERSION = "coverage-v3-2026.10.04"
PROPOSAL_GENERATOR_VERSION = "1.0.0"
CASE_ENGINE_VERSION = "1.0.0"
EVIDENCE_LOG_VERSION = "1.0.0"
TRAINING_FOCUS_VERSION = "1.0.0"
MODE_CONTROLLER_VERSION = "1.0.0"
VOICE_PROFILE_VERSION = "1.0.0"

MIN_CUSTOMER_AGE = 30
MAX_CUSTOMER_AGE = 79
SIMULATION_REFERENCE_DATE = "2026-10-04"
MAX_CONTRACTS_V1 = 7  # fixed to the approved 7-contract Excel template width (D:J)

PORTFOLIO_ARCHETYPES = (
    "BALANCED",
    "UNDERINSURED",
    "OVERINSURED",
    "DUPLICATED",
    "OUTDATED",
    "RENEWAL_HEAVY",
    "GAP_SPECIFIC",
    "MIXED",
)

CONSULTATION_DIFFICULTIES = ("easy", "standard", "hard")
INSURANCE_COMPLEXITIES = ("low", "medium", "high")
INTERACTION_MODES = ("TEXT", "VOICE")
TRAINING_MODES = ("GUIDE", "COACH", "SOLO", "ASSESSMENT")
