-- =========================================================
-- HWARANG PLATFORM
-- FEATURE PERMISSIONS + SUPER ADMIN MANAGEMENT v1
--
-- V6.0 (01~06) 적용 후 1회 실행합니다.
-- =========================================================

begin;

-- ---------------------------------------------------------
-- 1. 세부 기능 권한 마스터
-- ---------------------------------------------------------
create table if not exists public.hwarang_permissions (
    permission_code text primary key,
    app_code text not null check (app_code in ('workspace','calculator','academy')),
    group_label text not null,
    display_name text not null,
    description text not null default '',
    sort_order integer not null default 0,
    default_granted boolean not null default true,
    is_active boolean not null default true,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create table if not exists public.hwarang_user_permissions (
    user_id uuid not null references public.profiles(id) on delete cascade,
    permission_code text not null references public.hwarang_permissions(permission_code) on delete cascade,
    is_allowed boolean not null,
    updated_by uuid references public.profiles(id) on delete set null,
    updated_at timestamptz not null default now(),
    primary key (user_id, permission_code)
);

create index if not exists hwarang_user_permissions_user_idx
on public.hwarang_user_permissions(user_id);

-- 관리 이력
create table if not exists public.hwarang_admin_audit_log (
    id bigint generated by default as identity primary key,
    actor_user_id uuid not null references public.profiles(id) on delete restrict,
    target_user_id uuid references public.profiles(id) on delete set null,
    action text not null,
    details jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default now()
);

create index if not exists hwarang_admin_audit_log_created_idx
on public.hwarang_admin_audit_log(created_at desc);

-- ---------------------------------------------------------
-- 2. 권한 마스터 데이터
-- default_granted는 기존 Basic 사용자 경험을 최대한 유지합니다.
-- ---------------------------------------------------------
insert into public.hwarang_permissions
(permission_code, app_code, group_label, display_name, description, sort_order, default_granted)
values
('workspace.consultation','workspace','상담','상담 지원','상담 질문지 제작 등 상담 준비 기능',10,true),
('workspace.coverage_analysis','workspace','상담','보장 분석','보장분석 및 실손 세대 비교 기능',20,true),
('workspace.remodeling','workspace','상담','보험 리모델링','보험 리모델링 기능',30,false),
('workspace.comparison_tools','workspace','계산·비교','비교 계산','적금·단기납, 갱신·비갱신 비교 기능',40,false),
('workspace.customer_materials','workspace','고객자료','고객 전달자료','고객용 비교표 및 보험금 청구 가이드',50,true),
('workspace.official_resources','workspace','자료','원수사·공식자료','원수사 및 공식자료 포털',60,true),
('workspace.performance_basic','workspace','실적','개인 실적 도구','컨벤션·썸머 등 개인 실적 도구',70,true),
('workspace.performance_management','workspace','실적','관리 실적·수수료','매니저 업적 및 수수료 관리 도구',80,false),
('calculator.insurance_basic','calculator','계산기','보험 기본','보험나이·상령일·총납입 등',110,true),
('calculator.coverage_living','calculator','계산기','보장·생활자금','생활자금·치료비·보장 관련 계산',120,true),
('calculator.pension_retirement','calculator','계산기','연금·은퇴','연금·퇴직·은퇴 관련 계산',130,true),
('calculator.finance_investment','calculator','계산기','재무·투자','목표자금·복리·수익률 관련 계산',140,true),
('calculator.personal_tax','calculator','계산기','개인·부동산 세금','소득세·양도세·부동산 세금 관련 계산',150,true),
('calculator.inheritance_succession','calculator','계산기','상속·증여·승계','상속·증여·가업승계 관련 계산',160,true),
('calculator.corporate_strategy','calculator','계산기','법인·대표 전략','대표자 의사결정 및 법인 전략 계산',170,true),
('calculator.corporate_practice','calculator','계산기','사업·법인 실무','세무·노무·법인 실무 계산',180,true),
('academy.simulator','academy','교육','AI 상담 시뮬레이터','AI 상담 시뮬레이터 이용',210,true),
('academy.new_hire','academy','교육','신입교육','30·60·90일 신입교육 과정',220,true),
('academy.consultation','academy','교육','상담교육','TA·1차·2차 상담교육',230,true),
('academy.insurance_practice','academy','교육','보험실무','보장분석·계약·청구 실무교육',240,true),
('academy.assessment','academy','교육','시험·평가','지식 및 상담 역량 평가',250,true),
('academy.library','academy','교육','교육자료실','교육자료실 이용',260,true),
('academy.my_learning','academy','교육','나의학습','개인 학습·평가·성장 기록',270,true)
on conflict (permission_code) do update set
    app_code = excluded.app_code,
    group_label = excluded.group_label,
    display_name = excluded.display_name,
    description = excluded.description,
    sort_order = excluded.sort_order,
    default_granted = excluded.default_granted,
    is_active = true,
    updated_at = now();

-- ---------------------------------------------------------
-- 3. 최고관리자는 모든 세부 기능 허용, 일반 사용자는 override 또는 기본값
-- ---------------------------------------------------------
create or replace function public.get_hwarang_effective_permissions(p_user_id uuid)
returns table(permission_code text)
language sql
stable
security definer
set search_path = ''
as $$
    select perm.permission_code
    from public.hwarang_permissions perm
    join public.profiles p on p.id = p_user_id and p.is_active = true
    left join public.hwarang_user_permissions up
      on up.user_id = p_user_id
     and up.permission_code = perm.permission_code
    where perm.is_active = true
      and (
          p.role = 'super_admin'
          or coalesce(up.is_allowed, perm.default_granted) = true
      )
    order by perm.sort_order, perm.permission_code;
$$;

revoke all on function public.get_hwarang_effective_permissions(uuid)
from public, anon, authenticated;
grant execute on function public.get_hwarang_effective_permissions(uuid)
to service_role;

-- ---------------------------------------------------------
-- 4. 최고관리자 전용 일괄 계정/권한 변경 RPC
-- admin은 구조만 유지하며 이 함수 호출 권한을 자동으로 갖지 않습니다.
-- ---------------------------------------------------------
create or replace function public.admin_apply_hwarang_user(
    p_actor_user_id uuid,
    p_target_user_id uuid,
    p_display_name text,
    p_role text,
    p_is_active boolean,
    p_organization_unit_id uuid,
    p_position_code text,
    p_app_access jsonb,
    p_permissions jsonb
)
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare
    v_old_role text;
    v_old_active boolean;
    v_key text;
    v_value text;
begin
    if not exists (
        select 1 from public.profiles
        where id = p_actor_user_id
          and role = 'super_admin'
          and is_active = true
    ) then
        raise exception 'SUPER_ADMIN_REQUIRED';
    end if;

    if p_role not in ('user','admin','super_admin') then
        raise exception 'INVALID_SYSTEM_ROLE';
    end if;

    if p_display_name is null or btrim(p_display_name) = '' or char_length(btrim(p_display_name)) > 60 then
        raise exception 'INVALID_DISPLAY_NAME';
    end if;

    if not exists (select 1 from public.positions where code = p_position_code and is_active = true) then
        raise exception 'INVALID_POSITION';
    end if;

    if p_organization_unit_id is null or not exists (
        select 1 from public.organization_units where id = p_organization_unit_id and is_active = true
    ) then
        raise exception 'INVALID_ORGANIZATION';
    end if;

    select role, is_active into v_old_role, v_old_active
    from public.profiles where id = p_target_user_id for update;
    if not found then
        raise exception 'TARGET_USER_NOT_FOUND';
    end if;

    -- 본인 최고관리자 계정이 잠기는 것을 방지
    if p_target_user_id = p_actor_user_id then
        if p_role <> 'super_admin' or p_is_active = false then
            raise exception 'CANNOT_DEMOTE_OR_DISABLE_SELF';
        end if;
        if coalesce((p_app_access ->> 'workspace')::boolean, false) = false then
            raise exception 'CANNOT_DISABLE_OWN_WORKSPACE';
        end if;
    end if;

    -- 마지막 활성 최고관리자를 제거하지 못하도록 보호
    if v_old_role = 'super_admin' and v_old_active = true
       and (p_role <> 'super_admin' or p_is_active = false)
       and not exists (
           select 1 from public.profiles
           where id <> p_target_user_id
             and role = 'super_admin'
             and is_active = true
       ) then
        raise exception 'LAST_SUPER_ADMIN_REQUIRED';
    end if;

    update public.profiles
    set display_name = btrim(p_display_name),
        role = p_role,
        is_active = p_is_active,
        organization_unit_id = p_organization_unit_id,
        position_code = p_position_code,
        updated_at = now()
    where id = p_target_user_id;

    for v_key, v_value in select key, value from jsonb_each_text(coalesce(p_app_access, '{}'::jsonb)) loop
        if v_key not in ('workspace','calculator','academy') then
            raise exception 'INVALID_APP_CODE';
        end if;
        insert into public.hwarang_app_access(user_id, app_code, is_enabled, updated_at)
        values (p_target_user_id, v_key, v_value::boolean, now())
        on conflict (user_id, app_code) do update
        set is_enabled = excluded.is_enabled,
            updated_at = now();
    end loop;

    for v_key, v_value in select key, value from jsonb_each_text(coalesce(p_permissions, '{}'::jsonb)) loop
        if not exists (
            select 1 from public.hwarang_permissions
            where permission_code = v_key and is_active = true
        ) then
            raise exception 'INVALID_PERMISSION_CODE';
        end if;
        insert into public.hwarang_user_permissions(user_id, permission_code, is_allowed, updated_by, updated_at)
        values (p_target_user_id, v_key, v_value::boolean, p_actor_user_id, now())
        on conflict (user_id, permission_code) do update
        set is_allowed = excluded.is_allowed,
            updated_by = excluded.updated_by,
            updated_at = now();
    end loop;

    insert into public.hwarang_admin_audit_log(actor_user_id, target_user_id, action, details)
    values (
        p_actor_user_id,
        p_target_user_id,
        'account_permissions_updated',
        jsonb_build_object(
            'role', p_role,
            'is_active', p_is_active,
            'organization_unit_id', p_organization_unit_id,
            'position_code', p_position_code,
            'app_access', coalesce(p_app_access, '{}'::jsonb),
            'permissions', coalesce(p_permissions, '{}'::jsonb)
        )
    );
end;
$$;

revoke all on function public.admin_apply_hwarang_user(uuid,uuid,text,text,boolean,uuid,text,jsonb,jsonb)
from public, anon, authenticated;
grant execute on function public.admin_apply_hwarang_user(uuid,uuid,text,text,boolean,uuid,text,jsonb,jsonb)
to service_role;

-- ---------------------------------------------------------
-- 5. RLS / Data API grants
-- ---------------------------------------------------------
alter table public.hwarang_permissions enable row level security;
alter table public.hwarang_user_permissions enable row level security;
alter table public.hwarang_admin_audit_log enable row level security;

revoke all on table public.hwarang_permissions from anon, authenticated;
revoke all on table public.hwarang_user_permissions from anon, authenticated;
revoke all on table public.hwarang_admin_audit_log from anon, authenticated;

grant select, insert, update, delete on table public.hwarang_permissions to service_role;
grant select, insert, update, delete on table public.hwarang_user_permissions to service_role;
grant select, insert on table public.hwarang_admin_audit_log to service_role;

-- 관리자 View는 기존 이름을 유지하면서 권한 관련 테이블과 함께 사용
revoke all on table public.profiles_admin_view from anon, authenticated;
grant select on table public.profiles_admin_view to service_role;

commit;
