-- =========================================================
-- HWARANG PLATFORM
-- 09 Admin Operations + AI Guardrails + Training Credit v1
--
-- Apply ONCE after 01~08.
-- No OpenAI key is required.
-- AI is fail-closed: disabled by default.
-- =========================================================

begin;

-- 1) AI permission extensions
insert into public.hwarang_permissions
(permission_code, app_code, group_label, display_name, description, sort_order, default_granted)
values
('academy.voice_simulator','academy','교육','AI 음성 시뮬레이터','Voice/Realtime 상담 시뮬레이터 이용 권한',280,false),
('academy.formal_ai_assessment','academy','교육','AI 정식 평가','AI Evaluator 기반 정식 평가보고서 생성 권한',290,false)
on conflict (permission_code) do update set
    app_code = excluded.app_code,
    group_label = excluded.group_label,
    display_name = excluded.display_name,
    description = excluded.description,
    sort_order = excluded.sort_order,
    default_granted = excluded.default_granted,
    is_active = true,
    updated_at = now();

-- 2) Login/session history
create table if not exists public.hwarang_user_sessions (
    id uuid primary key default gen_random_uuid(),
    user_id uuid not null references public.profiles(id) on delete cascade,
    source_app text not null default 'workspace'
        check (source_app in ('workspace','calculator','academy')),
    status text not null default 'active'
        check (status in ('active','closed','expired')),
    login_at timestamptz not null default now(),
    last_seen_at timestamptz not null default now(),
    logout_at timestamptz,
    metadata jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default now()
);
create index if not exists hwarang_user_sessions_user_login_idx
    on public.hwarang_user_sessions(user_id, login_at desc);
create index if not exists hwarang_user_sessions_active_idx
    on public.hwarang_user_sessions(status, last_seen_at desc)
    where status='active';

-- 3) Meaningful activity only; do NOT copy customer text/file contents here.
create table if not exists public.hwarang_activity_log (
    id bigint generated by default as identity primary key,
    user_id uuid references public.profiles(id) on delete set null,
    platform_session_id uuid references public.hwarang_user_sessions(id) on delete set null,
    app_code text not null
        check (app_code in ('workspace','calculator','academy','platform')),
    event_code text not null,
    feature_code text,
    outcome text not null default 'success'
        check (outcome in ('success','info','blocked','failed')),
    metadata jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default now()
);
create index if not exists hwarang_activity_log_user_created_idx
    on public.hwarang_activity_log(user_id, created_at desc);
create index if not exists hwarang_activity_log_event_created_idx
    on public.hwarang_activity_log(event_code, created_at desc);
create index if not exists hwarang_activity_log_app_created_idx
    on public.hwarang_activity_log(app_code, created_at desc);

-- 4) Global AI runtime switch. Disabled until super_admin explicitly enables it.
create table if not exists public.hwarang_ai_runtime_config (
    config_id smallint primary key default 1 check (config_id=1),
    service_enabled boolean not null default false,
    text_enabled boolean not null default false,
    voice_enabled boolean not null default false,
    assessment_enabled boolean not null default false,
    soft_limit_percent integer not null default 80 check (soft_limit_percent between 1 and 99),
    contact_label text not null default '박병선 팀장에게 이용량 추가 문의',
    contact_url text not null default 'https://open.kakao.com/o/sFxdv4Rf',
    updated_by uuid references public.profiles(id) on delete set null,
    updated_at timestamptz not null default now()
);
insert into public.hwarang_ai_runtime_config(config_id)
values (1)
on conflict (config_id) do nothing;

-- 5) Training credit account + immutable ledger
create table if not exists public.hwarang_ai_credit_accounts (
    user_id uuid primary key references public.profiles(id) on delete cascade,
    allocation_credits bigint not null default 0 check (allocation_credits >= 0),
    balance_credits bigint not null default 0 check (balance_credits >= 0),
    reserved_credits bigint not null default 0 check (reserved_credits >= 0),
    updated_at timestamptz not null default now(),
    check (reserved_credits <= balance_credits)
);
insert into public.hwarang_ai_credit_accounts(user_id)
select id from public.profiles
on conflict (user_id) do nothing;

create table if not exists public.hwarang_ai_request_registry (
    request_id uuid primary key default gen_random_uuid(),
    idempotency_key text not null unique,
    user_id uuid not null references public.profiles(id) on delete cascade,
    academy_session_id uuid references public.academy_sessions(id) on delete set null,
    turn_no integer,
    purpose text not null check (purpose in ('CUSTOMER','COACH','EVALUATOR','VOICE')),
    interaction_mode text not null default 'TEXT'
        check (interaction_mode in ('TEXT','VOICE')),
    status text not null default 'reserved'
        check (status in ('reserved','processing','completed','failed','blocked','expired')),
    reserved_credits bigint not null default 0 check (reserved_credits >= 0),
    actual_credits bigint not null default 0 check (actual_credits >= 0),
    block_reason text,
    created_at timestamptz not null default now(),
    started_at timestamptz,
    completed_at timestamptz,
    expires_at timestamptz not null default (now() + interval '10 minutes'),
    metadata jsonb not null default '{}'::jsonb
);
create index if not exists hwarang_ai_request_user_created_idx
    on public.hwarang_ai_request_registry(user_id, created_at desc);
create index if not exists hwarang_ai_request_session_turn_idx
    on public.hwarang_ai_request_registry(academy_session_id, turn_no, purpose);
create index if not exists hwarang_ai_request_expiry_idx
    on public.hwarang_ai_request_registry(status, expires_at);

create table if not exists public.hwarang_ai_credit_ledger (
    id bigint generated by default as identity primary key,
    user_id uuid not null references public.profiles(id) on delete cascade,
    entry_type text not null check (entry_type in ('grant','revoke','consume','refund','reset','adjust')),
    delta_credits bigint not null,
    balance_after bigint not null check (balance_after >= 0),
    allocation_after bigint not null check (allocation_after >= 0),
    request_id uuid references public.hwarang_ai_request_registry(request_id) on delete set null,
    actor_user_id uuid references public.profiles(id) on delete set null,
    note text,
    created_at timestamptz not null default now()
);
create index if not exists hwarang_ai_credit_ledger_user_created_idx
    on public.hwarang_ai_credit_ledger(user_id, created_at desc);

-- 6) AI usage/cost ledger. Currency is admin-only; user UI uses Training Credit.
create table if not exists public.hwarang_ai_usage_log (
    id bigint generated by default as identity primary key,
    request_id uuid not null unique references public.hwarang_ai_request_registry(request_id) on delete restrict,
    user_id uuid not null references public.profiles(id) on delete cascade,
    academy_session_id uuid references public.academy_sessions(id) on delete set null,
    ai_role text not null check (ai_role in ('CUSTOMER','COACH','EVALUATOR','VOICE')),
    model text not null,
    input_tokens bigint not null default 0 check (input_tokens >= 0),
    cached_tokens bigint not null default 0 check (cached_tokens >= 0),
    output_tokens bigint not null default 0 check (output_tokens >= 0),
    audio_input_units bigint not null default 0 check (audio_input_units >= 0),
    audio_output_units bigint not null default 0 check (audio_output_units >= 0),
    unit_price_snapshot jsonb not null default '{}'::jsonb,
    calculated_cost_usd numeric(18,8) not null default 0 check (calculated_cost_usd >= 0),
    credits_charged bigint not null default 0 check (credits_charged >= 0),
    status text not null default 'completed' check (status in ('completed','failed')),
    latency_ms integer check (latency_ms is null or latency_ms >= 0),
    prompt_version text,
    model_version text,
    created_at timestamptz not null default now()
);
create index if not exists hwarang_ai_usage_user_created_idx
    on public.hwarang_ai_usage_log(user_id, created_at desc);
create index if not exists hwarang_ai_usage_model_created_idx
    on public.hwarang_ai_usage_log(model, created_at desc);

-- 7) Hierarchical limits. No normal-use requests-per-minute limit.
create table if not exists public.hwarang_ai_limit_policies (
    id bigint generated by default as identity primary key,
    scope_type text not null check (scope_type in ('platform','app','organization','user','session')),
    scope_key text not null,
    metric text not null check (metric in (
        'credits','session_turns','input_chars','output_tokens','voice_minutes','active_sessions'
    )),
    soft_limit numeric,
    hard_limit numeric,
    is_enabled boolean not null default true,
    metadata jsonb not null default '{}'::jsonb,
    updated_by uuid references public.profiles(id) on delete set null,
    updated_at timestamptz not null default now(),
    unique(scope_type, scope_key, metric),
    check (soft_limit is null or soft_limit >= 0),
    check (hard_limit is null or hard_limit >= 0),
    check (soft_limit is null or hard_limit is null or soft_limit <= hard_limit)
);

-- 8) One active AI session per user by default.
create table if not exists public.hwarang_ai_session_locks (
    user_id uuid primary key references public.profiles(id) on delete cascade,
    academy_session_id uuid not null unique references public.academy_sessions(id) on delete cascade,
    acquired_at timestamptz not null default now(),
    last_seen_at timestamptz not null default now(),
    expires_at timestamptz not null default (now() + interval '20 minutes')
);
create index if not exists hwarang_ai_session_locks_expiry_idx
    on public.hwarang_ai_session_locks(expires_at);

-- 9) New user bootstrap
create or replace function private.ensure_hwarang_ai_credit_account()
returns trigger
language plpgsql
security definer
set search_path=''
as $$
begin
    insert into public.hwarang_ai_credit_accounts(user_id)
    values (new.id)
    on conflict (user_id) do nothing;
    return new;
end;
$$;
revoke all on function private.ensure_hwarang_ai_credit_account() from public;
drop trigger if exists on_profile_created_ai_credit_account on public.profiles;
create trigger on_profile_created_ai_credit_account
after insert on public.profiles
for each row execute function private.ensure_hwarang_ai_credit_account();

-- 10) Login/activity RPCs
create or replace function public.open_hwarang_user_session(
    p_user_id uuid, p_source_app text default 'workspace'
)
returns uuid
language plpgsql
security definer
set search_path=''
as $$
declare v_id uuid;
begin
    if p_source_app not in ('workspace','calculator','academy') then
        raise exception 'INVALID_APP_CODE';
    end if;
    if not exists (
        select 1 from public.profiles where id=p_user_id and is_active=true
    ) then
        raise exception 'INACTIVE_USER';
    end if;

    insert into public.hwarang_user_sessions(user_id,source_app)
    values (p_user_id,p_source_app)
    returning id into v_id;

    update public.profiles set last_login_at=now() where id=p_user_id;

    insert into public.hwarang_activity_log(
        user_id,platform_session_id,app_code,event_code,outcome
    ) values (p_user_id,v_id,p_source_app,'LOGIN_SUCCESS','success');

    return v_id;
end;
$$;

create or replace function public.heartbeat_hwarang_user_session(
    p_session_id uuid, p_user_id uuid
)
returns void
language plpgsql
security definer
set search_path=''
as $$
begin
    update public.hwarang_user_sessions
    set last_seen_at=now()
    where id=p_session_id and user_id=p_user_id and status='active';
end;
$$;

create or replace function public.close_hwarang_user_session(
    p_session_id uuid, p_user_id uuid
)
returns void
language plpgsql
security definer
set search_path=''
as $$
declare v_app text;
begin
    select source_app into v_app
    from public.hwarang_user_sessions
    where id=p_session_id and user_id=p_user_id and status='active'
    for update;

    if found then
        update public.hwarang_user_sessions
        set last_seen_at=now(), logout_at=coalesce(logout_at,now()), status='closed'
        where id=p_session_id and user_id=p_user_id;

        insert into public.hwarang_activity_log(
            user_id,platform_session_id,app_code,event_code,outcome
        ) values (p_user_id,p_session_id,v_app,'LOGOUT','success');
    end if;
end;
$$;

create or replace function public.log_hwarang_activity(
    p_user_id uuid,
    p_platform_session_id uuid,
    p_app_code text,
    p_event_code text,
    p_feature_code text default null,
    p_outcome text default 'success',
    p_metadata jsonb default '{}'::jsonb
)
returns void
language plpgsql
security definer
set search_path=''
as $$
begin
    if p_app_code not in ('workspace','calculator','academy','platform') then
        raise exception 'INVALID_APP_CODE';
    end if;
    if p_outcome not in ('success','info','blocked','failed') then
        raise exception 'INVALID_ACTIVITY_OUTCOME';
    end if;
    if p_event_code is null or btrim(p_event_code)='' or char_length(p_event_code)>80 then
        raise exception 'INVALID_EVENT_CODE';
    end if;

    insert into public.hwarang_activity_log(
        user_id,platform_session_id,app_code,event_code,feature_code,outcome,metadata
    )
    values (
        p_user_id,p_platform_session_id,p_app_code,btrim(p_event_code),
        nullif(btrim(coalesce(p_feature_code,'')),''),
        p_outcome,coalesce(p_metadata,'{}'::jsonb)
    );
end;
$$;

-- 11) User-facing training-credit status
create or replace function public.get_hwarang_training_credit_status(p_user_id uuid)
returns table(
    allocation_credits bigint,
    balance_credits bigint,
    reserved_credits bigint,
    available_credits bigint,
    remaining_percent numeric,
    service_enabled boolean,
    text_enabled boolean,
    voice_enabled boolean,
    assessment_enabled boolean,
    soft_limit_percent integer,
    contact_label text,
    contact_url text
)
language sql
stable
security definer
set search_path=''
as $$
    select
        a.allocation_credits,
        a.balance_credits,
        a.reserved_credits,
        greatest(0::bigint,a.balance_credits-a.reserved_credits),
        case when a.allocation_credits<=0 then 0::numeric
             else round(greatest(
                 0::numeric,
                 (a.balance_credits-a.reserved_credits)::numeric
                 / a.allocation_credits::numeric * 100
             ),1)
        end,
        c.service_enabled,c.text_enabled,c.voice_enabled,c.assessment_enabled,
        c.soft_limit_percent,c.contact_label,c.contact_url
    from public.hwarang_ai_credit_accounts a
    cross join public.hwarang_ai_runtime_config c
    where a.user_id=p_user_id and c.config_id=1;
$$;

-- 12) Super-admin runtime settings
create or replace function public.admin_update_hwarang_ai_runtime(
    p_actor_user_id uuid,
    p_service_enabled boolean,
    p_text_enabled boolean,
    p_voice_enabled boolean,
    p_assessment_enabled boolean,
    p_soft_limit_percent integer,
    p_contact_label text,
    p_contact_url text
)
returns void
language plpgsql
security definer
set search_path=''
as $$
begin
    if not exists (
        select 1 from public.profiles
        where id=p_actor_user_id and role='super_admin' and is_active=true
    ) then raise exception 'SUPER_ADMIN_REQUIRED'; end if;

    if p_soft_limit_percent not between 1 and 99 then
        raise exception 'INVALID_SOFT_LIMIT';
    end if;

    update public.hwarang_ai_runtime_config
    set service_enabled=p_service_enabled,
        text_enabled=p_text_enabled,
        voice_enabled=p_voice_enabled,
        assessment_enabled=p_assessment_enabled,
        soft_limit_percent=p_soft_limit_percent,
        contact_label=coalesce(nullif(btrim(p_contact_label),''),contact_label),
        contact_url=coalesce(nullif(btrim(p_contact_url),''),contact_url),
        updated_by=p_actor_user_id,
        updated_at=now()
    where config_id=1;

    insert into public.hwarang_admin_audit_log(actor_user_id,action,details)
    values (
        p_actor_user_id,'ai_runtime_updated',
        jsonb_build_object(
            'service_enabled',p_service_enabled,
            'text_enabled',p_text_enabled,
            'voice_enabled',p_voice_enabled,
            'assessment_enabled',p_assessment_enabled,
            'soft_limit_percent',p_soft_limit_percent
        )
    );
end;
$$;

-- 13) Super-admin Training Credit adjustment
create or replace function public.admin_adjust_hwarang_ai_credits(
    p_actor_user_id uuid,
    p_target_user_id uuid,
    p_operation text,
    p_amount bigint,
    p_note text default null
)
returns table(allocation_credits bigint,balance_credits bigint,reserved_credits bigint)
language plpgsql
security definer
set search_path=''
as $$
declare
    v_account public.hwarang_ai_credit_accounts%rowtype;
    v_delta bigint;
begin
    if not exists (
        select 1 from public.profiles
        where id=p_actor_user_id and role='super_admin' and is_active=true
    ) then raise exception 'SUPER_ADMIN_REQUIRED'; end if;

    if p_operation not in ('grant','revoke','reset') then
        raise exception 'INVALID_CREDIT_OPERATION';
    end if;
    if p_amount<0 then raise exception 'INVALID_CREDIT_AMOUNT'; end if;

    insert into public.hwarang_ai_credit_accounts(user_id)
    values (p_target_user_id)
    on conflict (user_id) do nothing;

    select * into v_account
    from public.hwarang_ai_credit_accounts
    where user_id=p_target_user_id
    for update;

    if v_account.reserved_credits>0 and p_operation in ('revoke','reset') then
        raise exception 'AI_ACTIVE_RESERVATION';
    end if;

    if p_operation='grant' then
        v_delta:=p_amount;
        update public.hwarang_ai_credit_accounts
        set allocation_credits=allocation_credits+p_amount,
            balance_credits=balance_credits+p_amount,
            updated_at=now()
        where user_id=p_target_user_id
        returning * into v_account;
    elsif p_operation='revoke' then
        if p_amount>v_account.balance_credits then
            raise exception 'AI_CREDIT_REVOKE_EXCEEDS_BALANCE';
        end if;
        v_delta:=-p_amount;
        update public.hwarang_ai_credit_accounts
        set allocation_credits=greatest(0,allocation_credits-p_amount),
            balance_credits=balance_credits-p_amount,
            updated_at=now()
        where user_id=p_target_user_id
        returning * into v_account;
    else
        v_delta:=p_amount-v_account.balance_credits;
        update public.hwarang_ai_credit_accounts
        set allocation_credits=p_amount,
            balance_credits=p_amount,
            reserved_credits=0,
            updated_at=now()
        where user_id=p_target_user_id
        returning * into v_account;
    end if;

    insert into public.hwarang_ai_credit_ledger(
        user_id,entry_type,delta_credits,balance_after,allocation_after,actor_user_id,note
    )
    values (
        p_target_user_id,p_operation,v_delta,v_account.balance_credits,
        v_account.allocation_credits,p_actor_user_id,
        nullif(btrim(coalesce(p_note,'')),'')
    );

    insert into public.hwarang_admin_audit_log(actor_user_id,target_user_id,action,details)
    values (
        p_actor_user_id,p_target_user_id,'ai_credit_'||p_operation,
        jsonb_build_object(
            'amount',p_amount,'delta',v_delta,
            'balance_after',v_account.balance_credits,
            'allocation_after',v_account.allocation_credits,
            'note',p_note
        )
    );

    return query
    select v_account.allocation_credits,v_account.balance_credits,v_account.reserved_credits;
end;
$$;

-- 14) One active AI session lock
create or replace function public.acquire_hwarang_ai_session(
    p_user_id uuid, p_academy_session_id uuid
)
returns void
language plpgsql
security definer
set search_path=''
as $$
declare v_existing public.hwarang_ai_session_locks%rowtype;
begin
    delete from public.hwarang_ai_session_locks where expires_at<now();

    select * into v_existing
    from public.hwarang_ai_session_locks
    where user_id=p_user_id
    for update;

    if found and v_existing.academy_session_id<>p_academy_session_id then
        raise exception 'AI_ACTIVE_SESSION_EXISTS';
    end if;

    insert into public.hwarang_ai_session_locks(
        user_id,academy_session_id,acquired_at,last_seen_at,expires_at
    )
    values (
        p_user_id,p_academy_session_id,now(),now(),now()+interval '20 minutes'
    )
    on conflict (user_id) do update
    set last_seen_at=now(),expires_at=now()+interval '20 minutes'
    where public.hwarang_ai_session_locks.academy_session_id=excluded.academy_session_id;
end;
$$;

create or replace function public.release_hwarang_ai_session(
    p_user_id uuid, p_academy_session_id uuid
)
returns void
language sql
security definer
set search_path=''
as $$
    delete from public.hwarang_ai_session_locks
    where user_id=p_user_id and academy_session_id=p_academy_session_id;
$$;

-- 15) Reservation cleanup
create or replace function private.prune_hwarang_ai_reservations()
returns void
language plpgsql
security definer
set search_path=''
as $$
declare r record;
begin
    for r in
        select request_id,user_id,reserved_credits
        from public.hwarang_ai_request_registry
        where status in ('reserved','processing') and expires_at<now()
        for update skip locked
    loop
        update public.hwarang_ai_credit_accounts
        set reserved_credits=greatest(0,reserved_credits-r.reserved_credits),
            updated_at=now()
        where user_id=r.user_id;

        update public.hwarang_ai_request_registry
        set status='expired',completed_at=now()
        where request_id=r.request_id;
    end loop;
end;
$$;
revoke all on function private.prune_hwarang_ai_reservations() from public;

-- 16) Atomic reservation BEFORE external AI call
create or replace function public.reserve_hwarang_ai_request(
    p_user_id uuid,
    p_academy_session_id uuid,
    p_turn_no integer,
    p_purpose text,
    p_interaction_mode text,
    p_idempotency_key text,
    p_estimated_credits bigint
)
returns table(
    request_id uuid,
    request_status text,
    duplicate boolean,
    available_credits bigint
)
language plpgsql
security definer
set search_path=''
as $$
declare
    v_config public.hwarang_ai_runtime_config%rowtype;
    v_account public.hwarang_ai_credit_accounts%rowtype;
    v_request public.hwarang_ai_request_registry%rowtype;
    v_permissions text[];
begin
    perform private.prune_hwarang_ai_reservations();

    if p_purpose not in ('CUSTOMER','COACH','EVALUATOR','VOICE') then
        raise exception 'INVALID_AI_PURPOSE';
    end if;
    if p_interaction_mode not in ('TEXT','VOICE') then
        raise exception 'INVALID_INTERACTION_MODE';
    end if;
    if p_estimated_credits<=0 then raise exception 'INVALID_CREDIT_ESTIMATE'; end if;
    if p_idempotency_key is null or btrim(p_idempotency_key)='' or char_length(p_idempotency_key)>180 then
        raise exception 'INVALID_IDEMPOTENCY_KEY';
    end if;

    select * into v_request
    from public.hwarang_ai_request_registry
    where idempotency_key=p_idempotency_key;

    if found then
        if v_request.user_id<>p_user_id then raise exception 'IDEMPOTENCY_KEY_CONFLICT'; end if;
        select greatest(0,balance_credits-reserved_credits)
        into available_credits
        from public.hwarang_ai_credit_accounts
        where user_id=p_user_id;

        request_id:=v_request.request_id;
        request_status:=v_request.status;
        duplicate:=true;
        return next;
        return;
    end if;

    if not exists (
        select 1 from public.profiles where id=p_user_id and is_active=true
    ) then raise exception 'INACTIVE_USER'; end if;

    select * into v_config
    from public.hwarang_ai_runtime_config where config_id=1;

    if not v_config.service_enabled then raise exception 'AI_SERVICE_DISABLED'; end if;

    if p_interaction_mode='VOICE' then
        if not v_config.voice_enabled then raise exception 'AI_VOICE_DISABLED'; end if;
    else
        if not v_config.text_enabled then raise exception 'AI_TEXT_DISABLED'; end if;
    end if;

    if p_purpose='EVALUATOR' and not v_config.assessment_enabled then
        raise exception 'AI_ASSESSMENT_DISABLED';
    end if;

    select array_agg(permission_code) into v_permissions
    from public.get_hwarang_effective_permissions(p_user_id);

    if not ('academy.simulator'=any(coalesce(v_permissions,array[]::text[]))) then
        raise exception 'AI_SIMULATOR_PERMISSION_REQUIRED';
    end if;
    if p_interaction_mode='VOICE'
       and not ('academy.voice_simulator'=any(coalesce(v_permissions,array[]::text[]))) then
        raise exception 'AI_VOICE_PERMISSION_REQUIRED';
    end if;
    if p_purpose='EVALUATOR'
       and not ('academy.formal_ai_assessment'=any(coalesce(v_permissions,array[]::text[]))) then
        raise exception 'AI_ASSESSMENT_PERMISSION_REQUIRED';
    end if;

    insert into public.hwarang_ai_credit_accounts(user_id)
    values (p_user_id)
    on conflict (user_id) do nothing;

    select * into v_account
    from public.hwarang_ai_credit_accounts
    where user_id=p_user_id
    for update;

    if (v_account.balance_credits-v_account.reserved_credits)<p_estimated_credits then
        insert into public.hwarang_activity_log(
            user_id,app_code,event_code,feature_code,outcome,metadata
        ) values (
            p_user_id,'academy','AI_REQUEST_BLOCKED','academy.simulator','blocked',
            jsonb_build_object('reason','credit_exhausted','purpose',p_purpose)
        );
        raise exception 'AI_CREDIT_EXHAUSTED';
    end if;

    insert into public.hwarang_ai_request_registry(
        idempotency_key,user_id,academy_session_id,turn_no,purpose,
        interaction_mode,status,reserved_credits
    )
    values (
        btrim(p_idempotency_key),p_user_id,p_academy_session_id,p_turn_no,p_purpose,
        p_interaction_mode,'reserved',p_estimated_credits
    )
    returning * into v_request;

    update public.hwarang_ai_credit_accounts
    set reserved_credits=reserved_credits+p_estimated_credits,updated_at=now()
    where user_id=p_user_id
    returning * into v_account;

    request_id:=v_request.request_id;
    request_status:=v_request.status;
    duplicate:=false;
    available_credits:=greatest(0,v_account.balance_credits-v_account.reserved_credits);
    return next;
end;
$$;

-- 17) Finalize reservation after API result
create or replace function public.finalize_hwarang_ai_request(
    p_request_id uuid,
    p_result_status text,
    p_actual_credits bigint
)
returns table(balance_credits bigint,reserved_credits bigint,available_credits bigint)
language plpgsql
security definer
set search_path=''
as $$
declare
    v_request public.hwarang_ai_request_registry%rowtype;
    v_account public.hwarang_ai_credit_accounts%rowtype;
    v_other_reserved bigint;
begin
    if p_result_status not in ('completed','failed') then raise exception 'INVALID_AI_RESULT_STATUS'; end if;
    if p_actual_credits<0 then raise exception 'INVALID_CREDIT_AMOUNT'; end if;

    select * into v_request
    from public.hwarang_ai_request_registry
    where request_id=p_request_id
    for update;

    if not found then raise exception 'AI_REQUEST_NOT_FOUND'; end if;

    if v_request.status in ('completed','failed','expired') then
        select a.balance_credits,a.reserved_credits,
               greatest(0,a.balance_credits-a.reserved_credits)
        into balance_credits,reserved_credits,available_credits
        from public.hwarang_ai_credit_accounts a
        where a.user_id=v_request.user_id;
        return next;
        return;
    end if;

    select * into v_account
    from public.hwarang_ai_credit_accounts
    where user_id=v_request.user_id
    for update;

    if p_result_status='completed' then
        v_other_reserved:=greatest(0,v_account.reserved_credits-v_request.reserved_credits);

        if p_actual_credits>(v_account.balance_credits-v_other_reserved) then
            raise exception 'AI_CREDIT_RECONCILE_FAILED';
        end if;

        update public.hwarang_ai_credit_accounts
        set balance_credits=balance_credits-p_actual_credits,
            reserved_credits=v_other_reserved,
            updated_at=now()
        where user_id=v_request.user_id
        returning * into v_account;

        if p_actual_credits>0 then
            insert into public.hwarang_ai_credit_ledger(
                user_id,entry_type,delta_credits,balance_after,allocation_after,request_id,note
            ) values (
                v_request.user_id,'consume',-p_actual_credits,
                v_account.balance_credits,v_account.allocation_credits,
                v_request.request_id,'AI training usage'
            );
        end if;

        update public.hwarang_ai_request_registry
        set status='completed',actual_credits=p_actual_credits,completed_at=now()
        where request_id=p_request_id;
    else
        update public.hwarang_ai_credit_accounts
        set reserved_credits=greatest(0,reserved_credits-v_request.reserved_credits),
            updated_at=now()
        where user_id=v_request.user_id
        returning * into v_account;

        update public.hwarang_ai_request_registry
        set status='failed',actual_credits=0,completed_at=now()
        where request_id=p_request_id;
    end if;

    balance_credits:=v_account.balance_credits;
    reserved_credits:=v_account.reserved_credits;
    available_credits:=greatest(0,v_account.balance_credits-v_account.reserved_credits);
    return next;
end;
$$;

-- 18) Admin operational views
create or replace view public.hwarang_admin_user_operations_view
with (security_invoker=true)
as
select
    p.*,
    rs.last_seen_at as recent_seen_at,
    rs.status as recent_session_status,
    ra.event_code as recent_activity_code,
    ra.feature_code as recent_feature_code,
    ra.created_at as recent_activity_at,
    coalesce(ca.allocation_credits,0) as training_credit_allocation,
    coalesce(ca.balance_credits,0) as training_credit_balance,
    coalesce(ca.reserved_credits,0) as training_credit_reserved
from public.profiles_admin_view p
left join lateral (
    select s.last_seen_at,s.status
    from public.hwarang_user_sessions s
    where s.user_id=p.user_id
    order by s.last_seen_at desc
    limit 1
) rs on true
left join lateral (
    select a.event_code,a.feature_code,a.created_at
    from public.hwarang_activity_log a
    where a.user_id=p.user_id
    order by a.created_at desc
    limit 1
) ra on true
left join public.hwarang_ai_credit_accounts ca on ca.user_id=p.user_id;

create or replace view public.hwarang_admin_ai_usage_daily_view
with (security_invoker=true)
as
select
    date_trunc('day',created_at) as usage_day,
    user_id,ai_role,model,
    count(*) as request_count,
    sum(input_tokens) as input_tokens,
    sum(cached_tokens) as cached_tokens,
    sum(output_tokens) as output_tokens,
    sum(credits_charged) as credits_charged,
    sum(calculated_cost_usd) as calculated_cost_usd
from public.hwarang_ai_usage_log
group by 1,2,3,4;

-- 19) RLS / service-role only
alter table public.hwarang_user_sessions enable row level security;
alter table public.hwarang_activity_log enable row level security;
alter table public.hwarang_ai_runtime_config enable row level security;
alter table public.hwarang_ai_credit_accounts enable row level security;
alter table public.hwarang_ai_request_registry enable row level security;
alter table public.hwarang_ai_credit_ledger enable row level security;
alter table public.hwarang_ai_usage_log enable row level security;
alter table public.hwarang_ai_limit_policies enable row level security;
alter table public.hwarang_ai_session_locks enable row level security;

revoke all on table public.hwarang_user_sessions from anon,authenticated;
revoke all on table public.hwarang_activity_log from anon,authenticated;
revoke all on table public.hwarang_ai_runtime_config from anon,authenticated;
revoke all on table public.hwarang_ai_credit_accounts from anon,authenticated;
revoke all on table public.hwarang_ai_request_registry from anon,authenticated;
revoke all on table public.hwarang_ai_credit_ledger from anon,authenticated;
revoke all on table public.hwarang_ai_usage_log from anon,authenticated;
revoke all on table public.hwarang_ai_limit_policies from anon,authenticated;
revoke all on table public.hwarang_ai_session_locks from anon,authenticated;
revoke all on table public.hwarang_admin_user_operations_view from anon,authenticated;
revoke all on table public.hwarang_admin_ai_usage_daily_view from anon,authenticated;

grant select,insert,update,delete on table public.hwarang_user_sessions to service_role;
grant select,insert,update,delete on table public.hwarang_activity_log to service_role;
grant select,insert,update,delete on table public.hwarang_ai_runtime_config to service_role;
grant select,insert,update,delete on table public.hwarang_ai_credit_accounts to service_role;
grant select,insert,update,delete on table public.hwarang_ai_request_registry to service_role;
grant select,insert,update,delete on table public.hwarang_ai_credit_ledger to service_role;
grant select,insert,update,delete on table public.hwarang_ai_usage_log to service_role;
grant select,insert,update,delete on table public.hwarang_ai_limit_policies to service_role;
grant select,insert,update,delete on table public.hwarang_ai_session_locks to service_role;
grant select on table public.hwarang_admin_user_operations_view to service_role;
grant select on table public.hwarang_admin_ai_usage_daily_view to service_role;

revoke all on function public.open_hwarang_user_session(uuid,text) from public,anon,authenticated;
revoke all on function public.heartbeat_hwarang_user_session(uuid,uuid) from public,anon,authenticated;
revoke all on function public.close_hwarang_user_session(uuid,uuid) from public,anon,authenticated;
revoke all on function public.log_hwarang_activity(uuid,uuid,text,text,text,text,jsonb) from public,anon,authenticated;
revoke all on function public.get_hwarang_training_credit_status(uuid) from public,anon,authenticated;
revoke all on function public.admin_update_hwarang_ai_runtime(uuid,boolean,boolean,boolean,boolean,integer,text,text) from public,anon,authenticated;
revoke all on function public.admin_adjust_hwarang_ai_credits(uuid,uuid,text,bigint,text) from public,anon,authenticated;
revoke all on function public.acquire_hwarang_ai_session(uuid,uuid) from public,anon,authenticated;
revoke all on function public.release_hwarang_ai_session(uuid,uuid) from public,anon,authenticated;
revoke all on function public.reserve_hwarang_ai_request(uuid,uuid,integer,text,text,text,bigint) from public,anon,authenticated;
revoke all on function public.finalize_hwarang_ai_request(uuid,text,bigint) from public,anon,authenticated;

grant execute on function public.open_hwarang_user_session(uuid,text) to service_role;
grant execute on function public.heartbeat_hwarang_user_session(uuid,uuid) to service_role;
grant execute on function public.close_hwarang_user_session(uuid,uuid) to service_role;
grant execute on function public.log_hwarang_activity(uuid,uuid,text,text,text,text,jsonb) to service_role;
grant execute on function public.get_hwarang_training_credit_status(uuid) to service_role;
grant execute on function public.admin_update_hwarang_ai_runtime(uuid,boolean,boolean,boolean,boolean,integer,text,text) to service_role;
grant execute on function public.admin_adjust_hwarang_ai_credits(uuid,uuid,text,bigint,text) to service_role;
grant execute on function public.acquire_hwarang_ai_session(uuid,uuid) to service_role;
grant execute on function public.release_hwarang_ai_session(uuid,uuid) to service_role;
grant execute on function public.reserve_hwarang_ai_request(uuid,uuid,integer,text,text,text,bigint) to service_role;
grant execute on function public.finalize_hwarang_ai_request(uuid,text,bigint) to service_role;

commit;
