-- =========================================================
-- HWARANG PLATFORM
-- 10 PRE-API FINALIZATION v1
--
-- Apply ONCE after 09_Admin_Operations_AI_Guardrails.sql
-- No OpenAI key is required.
--
-- Finalized policies:
-- - TEXT / COACH / EVALUATOR share Training Credit.
-- - VOICE uses a completely separate voice-time allowance.
-- - No normal-use requests-per-minute limit.
-- - One active AI simulator session per user.
-- - AI remains fail-closed until super_admin enables it.
-- - Voice V1 target model: GPT-Live-1.
-- =========================================================

begin;

-- ---------------------------------------------------------
-- 1. Separate VOICE allowance account / ledger
-- ---------------------------------------------------------
create table if not exists public.hwarang_voice_accounts (
    user_id uuid primary key references public.profiles(id) on delete cascade,
    allocation_seconds bigint not null default 0 check (allocation_seconds >= 0),
    balance_seconds bigint not null default 0 check (balance_seconds >= 0),
    reserved_seconds bigint not null default 0 check (reserved_seconds >= 0),
    updated_at timestamptz not null default now(),
    check (reserved_seconds <= balance_seconds)
);

insert into public.hwarang_voice_accounts(user_id)
select id from public.profiles
on conflict (user_id) do nothing;

create table if not exists public.hwarang_voice_ledger (
    id bigint generated by default as identity primary key,
    user_id uuid not null references public.profiles(id) on delete cascade,
    entry_type text not null
        check (entry_type in ('grant','revoke','consume','refund','reset','adjust')),
    delta_seconds bigint not null,
    balance_after_seconds bigint not null check (balance_after_seconds >= 0),
    allocation_after_seconds bigint not null check (allocation_after_seconds >= 0),
    request_id uuid references public.hwarang_ai_request_registry(request_id) on delete set null,
    actor_user_id uuid references public.profiles(id) on delete set null,
    note text,
    created_at timestamptz not null default now()
);

create index if not exists hwarang_voice_ledger_user_created_idx
on public.hwarang_voice_ledger(user_id, created_at desc);

-- Existing request/usage tables are extended rather than replaced.
alter table public.hwarang_ai_request_registry
    add column if not exists billing_bucket text not null default 'TRAINING',
    add column if not exists reserved_voice_seconds bigint not null default 0,
    add column if not exists actual_voice_seconds bigint not null default 0;

do $$
begin
    if not exists (
        select 1
        from pg_constraint
        where conname = 'hwarang_ai_request_billing_bucket_check'
          and conrelid = 'public.hwarang_ai_request_registry'::regclass
    ) then
        alter table public.hwarang_ai_request_registry
            add constraint hwarang_ai_request_billing_bucket_check
            check (billing_bucket in ('TRAINING','VOICE'));
    end if;

    if not exists (
        select 1
        from pg_constraint
        where conname = 'hwarang_ai_request_reserved_voice_nonnegative'
          and conrelid = 'public.hwarang_ai_request_registry'::regclass
    ) then
        alter table public.hwarang_ai_request_registry
            add constraint hwarang_ai_request_reserved_voice_nonnegative
            check (reserved_voice_seconds >= 0);
    end if;

    if not exists (
        select 1
        from pg_constraint
        where conname = 'hwarang_ai_request_actual_voice_nonnegative'
          and conrelid = 'public.hwarang_ai_request_registry'::regclass
    ) then
        alter table public.hwarang_ai_request_registry
            add constraint hwarang_ai_request_actual_voice_nonnegative
            check (actual_voice_seconds >= 0);
    end if;
end
$$;

alter table public.hwarang_ai_usage_log
    add column if not exists voice_seconds_charged bigint not null default 0;

do $$
begin
    if not exists (
        select 1
        from pg_constraint
        where conname = 'hwarang_ai_usage_voice_seconds_nonnegative'
          and conrelid = 'public.hwarang_ai_usage_log'::regclass
    ) then
        alter table public.hwarang_ai_usage_log
            add constraint hwarang_ai_usage_voice_seconds_nonnegative
            check (voice_seconds_charged >= 0);
    end if;
end
$$;

-- ---------------------------------------------------------
-- 2. Versioned model policy.
-- Text model IDs remain intentionally unbound until the actual API connection.
-- Users never select models themselves.
-- ---------------------------------------------------------
create table if not exists public.hwarang_ai_model_policy (
    role_code text primary key
        check (role_code in ('CUSTOMER','COACH','EVALUATOR','VOICE')),
    display_name text not null,
    provider_model text,
    billing_bucket text not null
        check (billing_bucket in ('TRAINING','VOICE')),
    max_output_tokens integer
        check (max_output_tokens is null or max_output_tokens > 0),
    is_active boolean not null default true,
    policy_version text not null default 'pre-api-v1',
    updated_by uuid references public.profiles(id) on delete set null,
    updated_at timestamptz not null default now()
);

insert into public.hwarang_ai_model_policy
(role_code, display_name, provider_model, billing_bucket, max_output_tokens, policy_version)
values
('CUSTOMER',  '고객 AI',      null,         'TRAINING',  800,  'pre-api-v1'),
('COACH',     '코치 AI',      null,         'TRAINING', 1200,  'pre-api-v1'),
('EVALUATOR', '정식 평가 AI', null,         'TRAINING', 6000,  'pre-api-v1'),
('VOICE',     '음성 고객 AI', 'gpt-live-1', 'VOICE',    null,  'pre-api-v1')
on conflict (role_code) do update set
    display_name = excluded.display_name,
    billing_bucket = excluded.billing_bucket,
    max_output_tokens = excluded.max_output_tokens,
    policy_version = excluded.policy_version,
    is_active = true,
    provider_model = case
        when public.hwarang_ai_model_policy.role_code = 'VOICE'
            then excluded.provider_model
        else public.hwarang_ai_model_policy.provider_model
    end,
    updated_at = now();

-- ---------------------------------------------------------
-- 3. Default Guardrail policy
--
-- This intentionally does NOT include a requests-per-minute limit.
-- Normal honest simulator use should not feel rate-limited.
-- ---------------------------------------------------------
insert into public.hwarang_ai_limit_policies
(scope_type, scope_key, metric, soft_limit, hard_limit, metadata)
values
('app','academy',           'input_chars',     null, 2400, '{"reason":"prevent accidental document/prompt dumping"}'::jsonb),
('app','academy.customer',  'output_tokens',   null,  800, '{"role":"CUSTOMER"}'::jsonb),
('app','academy.coach',     'output_tokens',   null, 1200, '{"role":"COACH"}'::jsonb),
('app','academy.evaluator', 'output_tokens',   null, 6000, '{"role":"EVALUATOR"}'::jsonb),
('app','academy',           'session_turns',   null,   40, '{"matches DEEP mode maximum"}'::jsonb),
('app','academy.voice',     'voice_minutes',     25,   30, '{"voice_model":"gpt-live-1","reason":"safety cap above normal 12-20 minute DEEP session"}'::jsonb),
('app','academy',           'active_sessions', null,    1, '{"reason":"one active AI simulator session per user"}'::jsonb)
on conflict (scope_type, scope_key, metric) do update set
    soft_limit = excluded.soft_limit,
    hard_limit = excluded.hard_limit,
    metadata = excluded.metadata,
    is_enabled = true,
    updated_at = now();

-- ---------------------------------------------------------
-- 4. Create VOICE allowance for every future user.
-- ---------------------------------------------------------
create or replace function private.ensure_hwarang_voice_account()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
    insert into public.hwarang_voice_accounts(user_id)
    values (new.id)
    on conflict (user_id) do nothing;
    return new;
end;
$$;

revoke all on function private.ensure_hwarang_voice_account() from public;

drop trigger if exists on_profile_created_voice_account on public.profiles;
create trigger on_profile_created_voice_account
after insert on public.profiles
for each row execute function private.ensure_hwarang_voice_account();

-- ---------------------------------------------------------
-- 5. Unified user-facing entitlement status
-- User sees percentages/status, never API cost.
-- ---------------------------------------------------------
create or replace function public.get_hwarang_ai_entitlement_status(p_user_id uuid)
returns table(
    training_allocation_credits bigint,
    training_balance_credits bigint,
    training_reserved_credits bigint,
    training_available_credits bigint,
    training_remaining_percent numeric,

    voice_allocation_seconds bigint,
    voice_balance_seconds bigint,
    voice_reserved_seconds bigint,
    voice_available_seconds bigint,
    voice_remaining_percent numeric,

    service_enabled boolean,
    text_enabled boolean,
    voice_enabled boolean,
    assessment_enabled boolean,
    soft_limit_percent integer,
    contact_label text,
    contact_url text
)
language sql
stable
security definer
set search_path = ''
as $$
    select
        tc.allocation_credits,
        tc.balance_credits,
        tc.reserved_credits,
        greatest(0::bigint, tc.balance_credits - tc.reserved_credits),
        case
            when tc.allocation_credits <= 0 then 0::numeric
            else round(
                greatest(
                    0::numeric,
                    (tc.balance_credits - tc.reserved_credits)::numeric
                    / tc.allocation_credits::numeric * 100
                ),
                1
            )
        end,

        va.allocation_seconds,
        va.balance_seconds,
        va.reserved_seconds,
        greatest(0::bigint, va.balance_seconds - va.reserved_seconds),
        case
            when va.allocation_seconds <= 0 then 0::numeric
            else round(
                greatest(
                    0::numeric,
                    (va.balance_seconds - va.reserved_seconds)::numeric
                    / va.allocation_seconds::numeric * 100
                ),
                1
            )
        end,

        cfg.service_enabled,
        cfg.text_enabled,
        cfg.voice_enabled,
        cfg.assessment_enabled,
        cfg.soft_limit_percent,
        cfg.contact_label,
        cfg.contact_url
    from public.hwarang_ai_credit_accounts tc
    join public.hwarang_voice_accounts va
      on va.user_id = tc.user_id
    cross join public.hwarang_ai_runtime_config cfg
    where tc.user_id = p_user_id
      and cfg.config_id = 1;
$$;

-- ---------------------------------------------------------
-- 6. Super-admin VOICE allowance adjustment
-- Amount is supplied in whole minutes to keep admin UI simple.
-- ---------------------------------------------------------
create or replace function public.admin_adjust_hwarang_voice_minutes(
    p_actor_user_id uuid,
    p_target_user_id uuid,
    p_operation text,
    p_minutes bigint,
    p_note text default null
)
returns table(
    allocation_seconds bigint,
    balance_seconds bigint,
    reserved_seconds bigint
)
language plpgsql
security definer
set search_path = ''
as $$
declare
    v_account public.hwarang_voice_accounts%rowtype;
    v_seconds bigint;
    v_delta bigint;
begin
    if not exists (
        select 1
        from public.profiles
        where id = p_actor_user_id
          and role = 'super_admin'
          and is_active = true
    ) then
        raise exception 'SUPER_ADMIN_REQUIRED';
    end if;

    if p_operation not in ('grant','revoke','reset') then
        raise exception 'INVALID_VOICE_OPERATION';
    end if;

    if p_minutes < 0 then
        raise exception 'INVALID_VOICE_MINUTES';
    end if;

    v_seconds := p_minutes * 60;

    insert into public.hwarang_voice_accounts(user_id)
    values (p_target_user_id)
    on conflict (user_id) do nothing;

    select *
    into v_account
    from public.hwarang_voice_accounts
    where user_id = p_target_user_id
    for update;

    if v_account.reserved_seconds > 0 and p_operation in ('revoke','reset') then
        raise exception 'VOICE_ACTIVE_RESERVATION';
    end if;

    if p_operation = 'grant' then
        v_delta := v_seconds;

        update public.hwarang_voice_accounts
        set allocation_seconds = allocation_seconds + v_seconds,
            balance_seconds = balance_seconds + v_seconds,
            updated_at = now()
        where user_id = p_target_user_id
        returning * into v_account;

    elsif p_operation = 'revoke' then
        if v_seconds > v_account.balance_seconds then
            raise exception 'VOICE_REVOKE_EXCEEDS_BALANCE';
        end if;

        v_delta := -v_seconds;

        update public.hwarang_voice_accounts
        set allocation_seconds = greatest(0, allocation_seconds - v_seconds),
            balance_seconds = balance_seconds - v_seconds,
            updated_at = now()
        where user_id = p_target_user_id
        returning * into v_account;

    else
        v_delta := v_seconds - v_account.balance_seconds;

        update public.hwarang_voice_accounts
        set allocation_seconds = v_seconds,
            balance_seconds = v_seconds,
            reserved_seconds = 0,
            updated_at = now()
        where user_id = p_target_user_id
        returning * into v_account;
    end if;

    insert into public.hwarang_voice_ledger(
        user_id,
        entry_type,
        delta_seconds,
        balance_after_seconds,
        allocation_after_seconds,
        actor_user_id,
        note
    )
    values (
        p_target_user_id,
        p_operation,
        v_delta,
        v_account.balance_seconds,
        v_account.allocation_seconds,
        p_actor_user_id,
        nullif(btrim(coalesce(p_note,'')), '')
    );

    insert into public.hwarang_admin_audit_log(
        actor_user_id,
        target_user_id,
        action,
        details
    )
    values (
        p_actor_user_id,
        p_target_user_id,
        'voice_minutes_' || p_operation,
        jsonb_build_object(
            'minutes', p_minutes,
            'delta_seconds', v_delta,
            'balance_after_seconds', v_account.balance_seconds,
            'allocation_after_seconds', v_account.allocation_seconds,
            'note', p_note
        )
    );

    return query
    select
        v_account.allocation_seconds,
        v_account.balance_seconds,
        v_account.reserved_seconds;
end;
$$;

-- ---------------------------------------------------------
-- 6B. Active AI-session heartbeat.
-- Voice and long text sessions refresh this periodically; no click-level logging.
-- ---------------------------------------------------------
create or replace function public.heartbeat_hwarang_ai_session(
    p_user_id uuid,
    p_academy_session_id uuid
)
returns void
language plpgsql
security definer
set search_path = ''
as $$
begin
    update public.hwarang_ai_session_locks
    set last_seen_at = now(),
        expires_at = now() + interval '20 minutes'
    where user_id = p_user_id
      and academy_session_id = p_academy_session_id;

    if not found then
        raise exception 'AI_SESSION_LOCK_NOT_FOUND';
    end if;
end;
$$;

-- ---------------------------------------------------------
-- 7. Replace reservation pruning so both billing buckets recover safely.
-- ---------------------------------------------------------
create or replace function private.prune_hwarang_ai_reservations()
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare
    r record;
begin
    for r in
        select
            request_id,
            user_id,
            billing_bucket,
            reserved_credits,
            reserved_voice_seconds
        from public.hwarang_ai_request_registry
        where status in ('reserved','processing')
          and expires_at < now()
        for update skip locked
    loop
        if r.billing_bucket = 'VOICE' then
            update public.hwarang_voice_accounts
            set reserved_seconds = greatest(0, reserved_seconds - r.reserved_voice_seconds),
                updated_at = now()
            where user_id = r.user_id;
        else
            update public.hwarang_ai_credit_accounts
            set reserved_credits = greatest(0, reserved_credits - r.reserved_credits),
                updated_at = now()
            where user_id = r.user_id;
        end if;

        update public.hwarang_ai_request_registry
        set status = 'expired',
            completed_at = now()
        where request_id = r.request_id;
    end loop;
end;
$$;

revoke all on function private.prune_hwarang_ai_reservations() from public;

-- ---------------------------------------------------------
-- 8. TEXT / COACH / EVALUATOR reservation remains Training Credit only.
-- VOICE must use the separate voice-time reservation function below.
-- ---------------------------------------------------------
create or replace function public.reserve_hwarang_ai_request(
    p_user_id uuid,
    p_academy_session_id uuid,
    p_turn_no integer,
    p_purpose text,
    p_interaction_mode text,
    p_idempotency_key text,
    p_estimated_credits bigint
)
returns table(
    request_id uuid,
    request_status text,
    duplicate boolean,
    available_credits bigint
)
language plpgsql
security definer
set search_path = ''
as $$
declare
    v_config public.hwarang_ai_runtime_config%rowtype;
    v_account public.hwarang_ai_credit_accounts%rowtype;
    v_request public.hwarang_ai_request_registry%rowtype;
    v_permissions text[];
begin
    perform private.prune_hwarang_ai_reservations();

    if p_purpose not in ('CUSTOMER','COACH','EVALUATOR') then
        if p_purpose = 'VOICE' then
            raise exception 'VOICE_USE_SEPARATE_ALLOWANCE';
        end if;
        raise exception 'INVALID_AI_PURPOSE';
    end if;

    if p_interaction_mode <> 'TEXT' then
        raise exception 'TEXT_RESERVATION_REQUIRES_TEXT_MODE';
    end if;

    if p_estimated_credits <= 0 then
        raise exception 'INVALID_CREDIT_ESTIMATE';
    end if;

    if p_idempotency_key is null
       or btrim(p_idempotency_key) = ''
       or char_length(p_idempotency_key) > 180 then
        raise exception 'INVALID_IDEMPOTENCY_KEY';
    end if;

    select *
    into v_request
    from public.hwarang_ai_request_registry
    where idempotency_key = p_idempotency_key;

    if found then
        if v_request.user_id <> p_user_id then
            raise exception 'IDEMPOTENCY_KEY_CONFLICT';
        end if;

        select greatest(0, balance_credits - reserved_credits)
        into available_credits
        from public.hwarang_ai_credit_accounts
        where user_id = p_user_id;

        request_id := v_request.request_id;
        request_status := v_request.status;
        duplicate := true;
        return next;
        return;
    end if;

    if not exists (
        select 1
        from public.profiles
        where id = p_user_id
          and is_active = true
    ) then
        raise exception 'INACTIVE_USER';
    end if;

    select *
    into v_config
    from public.hwarang_ai_runtime_config
    where config_id = 1;

    if not v_config.service_enabled then
        raise exception 'AI_SERVICE_DISABLED';
    end if;

    if not v_config.text_enabled then
        raise exception 'AI_TEXT_DISABLED';
    end if;

    if p_purpose = 'EVALUATOR' and not v_config.assessment_enabled then
        raise exception 'AI_ASSESSMENT_DISABLED';
    end if;

    select array_agg(permission_code)
    into v_permissions
    from public.get_hwarang_effective_permissions(p_user_id);

    if not ('academy.simulator' = any(coalesce(v_permissions,array[]::text[]))) then
        raise exception 'AI_SIMULATOR_PERMISSION_REQUIRED';
    end if;

    if p_purpose = 'EVALUATOR'
       and not ('academy.formal_ai_assessment' = any(coalesce(v_permissions,array[]::text[]))) then
        raise exception 'AI_ASSESSMENT_PERMISSION_REQUIRED';
    end if;

    insert into public.hwarang_ai_credit_accounts(user_id)
    values (p_user_id)
    on conflict (user_id) do nothing;

    select *
    into v_account
    from public.hwarang_ai_credit_accounts
    where user_id = p_user_id
    for update;

    if (v_account.balance_credits - v_account.reserved_credits) < p_estimated_credits then
        insert into public.hwarang_activity_log(
            user_id, app_code, event_code, feature_code, outcome, metadata
        )
        values (
            p_user_id,
            'academy',
            'AI_REQUEST_BLOCKED',
            'academy.simulator',
            'blocked',
            jsonb_build_object('reason','training_credit_exhausted','purpose',p_purpose)
        );

        raise exception 'AI_CREDIT_EXHAUSTED';
    end if;

    insert into public.hwarang_ai_request_registry(
        idempotency_key,
        user_id,
        academy_session_id,
        turn_no,
        purpose,
        interaction_mode,
        billing_bucket,
        status,
        reserved_credits,
        reserved_voice_seconds
    )
    values (
        btrim(p_idempotency_key),
        p_user_id,
        p_academy_session_id,
        p_turn_no,
        p_purpose,
        'TEXT',
        'TRAINING',
        'reserved',
        p_estimated_credits,
        0
    )
    returning * into v_request;

    update public.hwarang_ai_credit_accounts
    set reserved_credits = reserved_credits + p_estimated_credits,
        updated_at = now()
    where user_id = p_user_id
    returning * into v_account;

    request_id := v_request.request_id;
    request_status := v_request.status;
    duplicate := false;
    available_credits := greatest(
        0,
        v_account.balance_credits - v_account.reserved_credits
    );

    return next;
end;
$$;

-- ---------------------------------------------------------
-- 9. VOICE reservation.
-- The caller requests a session budget; DB returns the allowed number of seconds.
-- The platform hard cap defaults to 30 minutes, which is above normal DEEP usage.
-- ---------------------------------------------------------
create or replace function public.reserve_hwarang_voice_request(
    p_user_id uuid,
    p_academy_session_id uuid,
    p_turn_no integer,
    p_idempotency_key text,
    p_requested_seconds bigint
)
returns table(
    request_id uuid,
    request_status text,
    duplicate boolean,
    allowed_voice_seconds bigint,
    available_voice_seconds bigint
)
language plpgsql
security definer
set search_path = ''
as $$
declare
    v_config public.hwarang_ai_runtime_config%rowtype;
    v_account public.hwarang_voice_accounts%rowtype;
    v_request public.hwarang_ai_request_registry%rowtype;
    v_permissions text[];
    v_hard_minutes numeric;
    v_hard_seconds bigint;
    v_allowed bigint;
begin
    perform private.prune_hwarang_ai_reservations();

    if p_requested_seconds <= 0 then
        raise exception 'INVALID_VOICE_SECONDS';
    end if;

    if p_idempotency_key is null
       or btrim(p_idempotency_key) = ''
       or char_length(p_idempotency_key) > 180 then
        raise exception 'INVALID_IDEMPOTENCY_KEY';
    end if;

    select *
    into v_request
    from public.hwarang_ai_request_registry
    where idempotency_key = p_idempotency_key;

    if found then
        if v_request.user_id <> p_user_id then
            raise exception 'IDEMPOTENCY_KEY_CONFLICT';
        end if;

        select greatest(0, balance_seconds - reserved_seconds)
        into available_voice_seconds
        from public.hwarang_voice_accounts
        where user_id = p_user_id;

        request_id := v_request.request_id;
        request_status := v_request.status;
        duplicate := true;
        allowed_voice_seconds := v_request.reserved_voice_seconds;
        return next;
        return;
    end if;

    if not exists (
        select 1
        from public.profiles
        where id = p_user_id
          and is_active = true
    ) then
        raise exception 'INACTIVE_USER';
    end if;

    select *
    into v_config
    from public.hwarang_ai_runtime_config
    where config_id = 1;

    if not v_config.service_enabled then
        raise exception 'AI_SERVICE_DISABLED';
    end if;

    if not v_config.voice_enabled then
        raise exception 'AI_VOICE_DISABLED';
    end if;

    select array_agg(permission_code)
    into v_permissions
    from public.get_hwarang_effective_permissions(p_user_id);

    if not ('academy.simulator' = any(coalesce(v_permissions,array[]::text[]))) then
        raise exception 'AI_SIMULATOR_PERMISSION_REQUIRED';
    end if;

    if not ('academy.voice_simulator' = any(coalesce(v_permissions,array[]::text[]))) then
        raise exception 'AI_VOICE_PERMISSION_REQUIRED';
    end if;

    insert into public.hwarang_voice_accounts(user_id)
    values (p_user_id)
    on conflict (user_id) do nothing;

    select *
    into v_account
    from public.hwarang_voice_accounts
    where user_id = p_user_id
    for update;

    select hard_limit
    into v_hard_minutes
    from public.hwarang_ai_limit_policies
    where scope_type = 'app'
      and scope_key = 'academy.voice'
      and metric = 'voice_minutes'
      and is_enabled = true
    limit 1;

    v_hard_seconds := greatest(
        60::bigint,
        floor(coalesce(v_hard_minutes,30) * 60)::bigint
    );

    v_allowed := least(
        p_requested_seconds,
        v_hard_seconds,
        greatest(0::bigint, v_account.balance_seconds - v_account.reserved_seconds)
    );

    if v_allowed <= 0 then
        insert into public.hwarang_activity_log(
            user_id, app_code, event_code, feature_code, outcome, metadata
        )
        values (
            p_user_id,
            'academy',
            'AI_REQUEST_BLOCKED',
            'academy.voice_simulator',
            'blocked',
            jsonb_build_object('reason','voice_allowance_exhausted')
        );

        raise exception 'VOICE_ALLOWANCE_EXHAUSTED';
    end if;

    insert into public.hwarang_ai_request_registry(
        idempotency_key,
        user_id,
        academy_session_id,
        turn_no,
        purpose,
        interaction_mode,
        billing_bucket,
        status,
        reserved_credits,
        reserved_voice_seconds
    )
    values (
        btrim(p_idempotency_key),
        p_user_id,
        p_academy_session_id,
        p_turn_no,
        'VOICE',
        'VOICE',
        'VOICE',
        'reserved',
        0,
        v_allowed
    )
    returning * into v_request;

    update public.hwarang_voice_accounts
    set reserved_seconds = reserved_seconds + v_allowed,
        updated_at = now()
    where user_id = p_user_id
    returning * into v_account;

    request_id := v_request.request_id;
    request_status := v_request.status;
    duplicate := false;
    allowed_voice_seconds := v_allowed;
    available_voice_seconds := greatest(
        0,
        v_account.balance_seconds - v_account.reserved_seconds
    );

    return next;
end;
$$;

-- ---------------------------------------------------------
-- 10. Finalize VOICE usage and return unused reserved seconds.
-- ---------------------------------------------------------
create or replace function public.finalize_hwarang_voice_request(
    p_request_id uuid,
    p_result_status text,
    p_actual_seconds bigint
)
returns table(
    balance_seconds bigint,
    reserved_seconds bigint,
    available_seconds bigint
)
language plpgsql
security definer
set search_path = ''
as $$
declare
    v_request public.hwarang_ai_request_registry%rowtype;
    v_account public.hwarang_voice_accounts%rowtype;
    v_other_reserved bigint;
begin
    if p_result_status not in ('completed','failed') then
        raise exception 'INVALID_AI_RESULT_STATUS';
    end if;

    if p_actual_seconds < 0 then
        raise exception 'INVALID_VOICE_SECONDS';
    end if;

    select *
    into v_request
    from public.hwarang_ai_request_registry
    where request_id = p_request_id
    for update;

    if not found then
        raise exception 'AI_REQUEST_NOT_FOUND';
    end if;

    if v_request.billing_bucket <> 'VOICE' then
        raise exception 'AI_REQUEST_NOT_VOICE';
    end if;

    if v_request.status in ('completed','failed','expired') then
        select
            a.balance_seconds,
            a.reserved_seconds,
            greatest(0, a.balance_seconds - a.reserved_seconds)
        into balance_seconds, reserved_seconds, available_seconds
        from public.hwarang_voice_accounts a
        where a.user_id = v_request.user_id;

        return next;
        return;
    end if;

    if p_actual_seconds > v_request.reserved_voice_seconds then
        raise exception 'VOICE_USAGE_EXCEEDS_RESERVATION';
    end if;

    select *
    into v_account
    from public.hwarang_voice_accounts
    where user_id = v_request.user_id
    for update;

    v_other_reserved := greatest(
        0,
        v_account.reserved_seconds - v_request.reserved_voice_seconds
    );

    if p_result_status = 'completed' then
        update public.hwarang_voice_accounts
        set balance_seconds = balance_seconds - p_actual_seconds,
            reserved_seconds = v_other_reserved,
            updated_at = now()
        where user_id = v_request.user_id
        returning * into v_account;

        if p_actual_seconds > 0 then
            insert into public.hwarang_voice_ledger(
                user_id,
                entry_type,
                delta_seconds,
                balance_after_seconds,
                allocation_after_seconds,
                request_id,
                note
            )
            values (
                v_request.user_id,
                'consume',
                -p_actual_seconds,
                v_account.balance_seconds,
                v_account.allocation_seconds,
                v_request.request_id,
                'Voice training usage'
            );
        end if;

        update public.hwarang_ai_request_registry
        set status = 'completed',
            actual_voice_seconds = p_actual_seconds,
            completed_at = now()
        where request_id = p_request_id;

    else
        update public.hwarang_voice_accounts
        set reserved_seconds = v_other_reserved,
            updated_at = now()
        where user_id = v_request.user_id
        returning * into v_account;

        update public.hwarang_ai_request_registry
        set status = 'failed',
            actual_voice_seconds = 0,
            completed_at = now()
        where request_id = p_request_id;
    end if;

    balance_seconds := v_account.balance_seconds;
    reserved_seconds := v_account.reserved_seconds;
    available_seconds := greatest(
        0,
        v_account.balance_seconds - v_account.reserved_seconds
    );

    return next;
end;
$$;

-- ---------------------------------------------------------
-- 11. Super-admin-only model policy update.
-- Text provider model IDs are filled only at API connection time.
-- ---------------------------------------------------------
create or replace function public.admin_update_hwarang_ai_model_policy(
    p_actor_user_id uuid,
    p_role_code text,
    p_provider_model text,
    p_max_output_tokens integer
)
returns void
language plpgsql
security definer
set search_path = ''
as $$
begin
    if not exists (
        select 1
        from public.profiles
        where id = p_actor_user_id
          and role = 'super_admin'
          and is_active = true
    ) then
        raise exception 'SUPER_ADMIN_REQUIRED';
    end if;

    if p_role_code not in ('CUSTOMER','COACH','EVALUATOR','VOICE') then
        raise exception 'INVALID_AI_ROLE';
    end if;

    if p_max_output_tokens is not null and p_max_output_tokens <= 0 then
        raise exception 'INVALID_OUTPUT_TOKEN_LIMIT';
    end if;

    update public.hwarang_ai_model_policy
    set provider_model = nullif(btrim(coalesce(p_provider_model,'')), ''),
        max_output_tokens = p_max_output_tokens,
        updated_by = p_actor_user_id,
        updated_at = now()
    where role_code = p_role_code;

    if not found then
        raise exception 'AI_ROLE_NOT_FOUND';
    end if;

    insert into public.hwarang_admin_audit_log(
        actor_user_id,
        action,
        details
    )
    values (
        p_actor_user_id,
        'ai_model_policy_updated',
        jsonb_build_object(
            'role_code', p_role_code,
            'provider_model', nullif(btrim(coalesce(p_provider_model,'')), ''),
            'max_output_tokens', p_max_output_tokens
        )
    );
end;
$$;

-- ---------------------------------------------------------
-- 12. Admin operations view: append VOICE allowance columns.
-- Existing column order is preserved; new columns are appended.
-- ---------------------------------------------------------
create or replace view public.hwarang_admin_user_operations_view
with (security_invoker = true)
as
select
    p.*,
    recent_session.last_seen_at as recent_seen_at,
    recent_session.status as recent_session_status,
    recent_activity.event_code as recent_activity_code,
    recent_activity.feature_code as recent_feature_code,
    recent_activity.created_at as recent_activity_at,
    coalesce(ca.allocation_credits,0) as training_credit_allocation,
    coalesce(ca.balance_credits,0) as training_credit_balance,
    coalesce(ca.reserved_credits,0) as training_credit_reserved,
    coalesce(va.allocation_seconds,0) as voice_allocation_seconds,
    coalesce(va.balance_seconds,0) as voice_balance_seconds,
    coalesce(va.reserved_seconds,0) as voice_reserved_seconds
from public.profiles_admin_view p
left join lateral (
    select s.last_seen_at, s.status
    from public.hwarang_user_sessions s
    where s.user_id = p.user_id
    order by s.last_seen_at desc
    limit 1
) recent_session on true
left join lateral (
    select a.event_code, a.feature_code, a.created_at
    from public.hwarang_activity_log a
    where a.user_id = p.user_id
    order by a.created_at desc
    limit 1
) recent_activity on true
left join public.hwarang_ai_credit_accounts ca
    on ca.user_id = p.user_id
left join public.hwarang_voice_accounts va
    on va.user_id = p.user_id;

-- ---------------------------------------------------------
-- 13. RLS / grants
-- ---------------------------------------------------------
alter table public.hwarang_voice_accounts enable row level security;
alter table public.hwarang_voice_ledger enable row level security;
alter table public.hwarang_ai_model_policy enable row level security;

revoke all on table public.hwarang_voice_accounts from anon, authenticated;
revoke all on table public.hwarang_voice_ledger from anon, authenticated;
revoke all on table public.hwarang_ai_model_policy from anon, authenticated;

grant select, insert, update, delete on table public.hwarang_voice_accounts to service_role;
grant select, insert, update, delete on table public.hwarang_voice_ledger to service_role;
grant select, insert, update, delete on table public.hwarang_ai_model_policy to service_role;

revoke all on function public.heartbeat_hwarang_ai_session(uuid,uuid)
from public, anon, authenticated;
revoke all on function public.get_hwarang_ai_entitlement_status(uuid)
from public, anon, authenticated;
revoke all on function public.admin_adjust_hwarang_voice_minutes(uuid,uuid,text,bigint,text)
from public, anon, authenticated;
revoke all on function public.reserve_hwarang_voice_request(uuid,uuid,integer,text,bigint)
from public, anon, authenticated;
revoke all on function public.finalize_hwarang_voice_request(uuid,text,bigint)
from public, anon, authenticated;
revoke all on function public.admin_update_hwarang_ai_model_policy(uuid,text,text,integer)
from public, anon, authenticated;

grant execute on function public.heartbeat_hwarang_ai_session(uuid,uuid)
to service_role;
grant execute on function public.get_hwarang_ai_entitlement_status(uuid)
to service_role;
grant execute on function public.admin_adjust_hwarang_voice_minutes(uuid,uuid,text,bigint,text)
to service_role;
grant execute on function public.reserve_hwarang_voice_request(uuid,uuid,integer,text,bigint)
to service_role;
grant execute on function public.finalize_hwarang_voice_request(uuid,text,bigint)
to service_role;
grant execute on function public.admin_update_hwarang_ai_model_policy(uuid,text,text,integer)
to service_role;

-- Refresh existing grants for the replaced Training Credit reservation function.
revoke all on function public.reserve_hwarang_ai_request(uuid,uuid,integer,text,text,text,bigint)
from public, anon, authenticated;
grant execute on function public.reserve_hwarang_ai_request(uuid,uuid,integer,text,text,text,bigint)
to service_role;

commit;
