[theme]
base = "light"
primaryColor = "#17233C"
backgroundColor = "#F7F6F2"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#17233C"
baseFontSize = 16

[browser]
gatherUsageStats = false

[server]
enableCORS = true
enableXsrfProtection = true

[logger]
level = "warning"
