[theme]
base = "light"
primaryColor = "#2D6AD5"
backgroundColor = "#F5F7FA"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#17233C"
baseFontSize = 16

[browser]
gatherUsageStats = false

[server]
enableCORS = true
enableXsrfProtection = true

[logger]
level = "warning"
